name: payment-service
namespace: eokarpova

# This will set the replicaset count more information can be found here: https://kubernetes.io/docs/concepts/workloads/controllers/replicaset/
replicaCount: 1

# This sets the container image more information can be found here: https://kubernetes.io/docs/concepts/containers/images/
image:
  repository: ghcr.io/polnaya-katuxa/ds-lab-04-payment-service
  # This sets the pull policy for images.
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: latest

config:
  port: 80
  logLevel: info
  postgres:
    host: payment-service-db
    port: 5432
    user: program
    password: test
    db: postgres
  services:
    cars_service: ""
    payment_service: ""
    rental_service: ""
  kafka:
    broker: ""
    cars_retry_topic: ""
    payment_retry_topic: ""
  jwksURL: http://keycloak.ds-labs-kub.tw1.ru/realms/ds-lab-05/protocol/openid-connect/certs
  servicePassword: 123
