openapi: 3.0.1
info:
  title: Rental Service
  version: "1.0"
servers:
  - url: http://localhost:8080
paths:
  /api/v1/rental:
    get:
      summary: Получить информацию о всех арендах пользователя
      operationId: GetUserRentals
      tags:
        - Rental Service API
      responses:
        "200":
          description: Информация обо всех арендах
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/RentalResponse"

    post:
      summary: Оформить аренду
      operationId: Create
      tags:
        - Rental Service API
      parameters:
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateRentalRequest"
      responses:
        "200":
          description: Информация об аренде
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/RentalResponse"
        "400":
          description: Ошибка валидации данных
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ValidationErrorResponse"

  /api/v1/rental/{rentalUid}:
    get:
      summary: Информация по конкретной аренде пользователя
      operationId: Get
      tags:
        - Rental Service API
      parameters:
        - name: rentalUid
          in: path
          description: UUID аренды
          required: true
          schema:
            type: string
            format: uuid
      responses:
        "200":
          description: Информация по конкретному бронированию
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/RentalResponse"
        "404":
          description: Аренда не найдена
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "403":
          description: Аренда не принадлежит пользователю
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

    delete:
      summary: Отмена аренды
      operationId: Cancel
      tags:
        - Rental Service API
      parameters:
        - name: rentalUid
          in: path
          description: UUID аренды
          required: true
          schema:
            type: string
            format: uuid
      responses:
        "204":
          description: Аренда успешно отменена
        "404":
          description: Аренда не найдена
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "403":
          description: Аренда не принадлежит пользователю
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

  /api/v1/rental/{rentalUid}/finish:
    post:
      summary: Завершение аренды
      operationId: Finish
      tags:
        - Rental Service API
      parameters:
        - name: rentalUid
          in: path
          description: UUID аренды
          required: true
          schema:
            type: string
            format: uuid
      responses:
        "204":
          description: Аренда успешно завершена
        "404":
          description: Аренда не найдена
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

  /manage/health:
    get:
      summary: Liveness probe
      operationId: Live
      responses:
        "200":
          description: Сервис работает

components:
  schemas:
    RentalResponse:
      type: object
      example:
        {
          "rentalUid": "4fd4fc0c-7840-483c-bcf5-3e2be7d4ea69",
          "status": "IN_PROGRESS",
          "dateFrom": "2021-10-08",
          "dateTo": "2021-10-11",
          "carUid": "109b42f3-198d-4c89-9276-a7520a7120ab",
          "paymentUid": "238c733c-fb1e-40a9-aadb-73cb8f90675d",
        }
      required:
        - rentalUid
        - status
        - dateFrom
        - dateTo
        - carUid
        - paymentUid
      properties:
        rentalUid:
          type: string
          description: UUID аренды
          format: uuid
        status:
          type: string
          description: Статус аренды
          enum:
            - IN_PROGRESS
            - FINISHED
            - CANCELED
        dateFrom:
          type: string
          description: Дата начала аренды
          format: ISO 8601
        dateTo:
          type: string
          description: Дата окончания аренды
          format: ISO 8601
        carUid:
          type: string
          format: uuid
          description: UUID автомобиля
        paymentUid:
          type: string
          format: uuid
          description: UUID платежа

    CreateRentalRequest:
      type: object
      example:
        {
          "carUid": "109b42f3-198d-4c89-9276-a7520a7120ab",
          "dateFrom": "2021-10-08",
          "dateTo": "2021-10-11",
          "paymentUid": "238c733c-fb1e-40a9-aadb-73cb8f90675d",
        }
      required:
        - dateFrom
        - dateTo
        - carUid
        - paymentUid
      properties:
        carUid:
          type: string
          format: uuid
          description: UUID автомобиля
        dateFrom:
          type: string
          description: Дата начала аренды
          format: ISO 8601
        dateTo:
          type: string
          description: Дата окончания аренды
          format: ISO 8601
        paymentUid:
          type: string
          format: uuid
          description: UUID платежа

    ErrorDescription:
      type: object
      required:
        - field
        - error
      properties:
        field:
          type: string
        error:
          type: string

    ErrorResponse:
      type: object
      required:
        - message
      properties:
        message:
          type: string
          description: Информация об ошибке

    ValidationErrorResponse:
      type: object
      required:
        - message
        - errors
      properties:
        message:
          type: string
          description: Информация об ошибке
        errors:
          type: array
          description: Массив полей с описанием ошибки
          items:
            $ref: "#/components/schemas/ErrorDescription"
